### ISSUE TITLE
Can you give some actual example commands?

### ISSUE THREAD

**Issue by nyck33** [andrewrproper/pandoc-folder#1]
I want to convert and combine a folder of .md files into a .pdf.  

Pandoc is confusing on its own but you are adding another layer of complexity.

Please give some example commands like we are 8 years old.

**Comment by andrewrproper** [comment]
Have you checked the Usage section, on the readme?

https://github.com/andrewrproper/pandoc-folder#usage

It shows that you need to set up a .pfy file and run that with pandoc-folder

I included an example book 
https://github.com/andrewrproper/pandoc-folder/tree/main/example-book

with an example .pfy file
https://github.com/andrewrproper/pandoc-folder/blob/main/example-book/.pandoc-folder/pandoc-folder-epub.pfy

You could try cloning this repo and running the bat file to build the example book
https://github.com/andrewrproper/pandoc-folder/blob/main/build-example-book.bat

Then you could edit the example book and re-run the bat file, to see the changes.

Is that enough to get you started?

**Comment by nyck33** [comment]
Hey Andrew, thanks so much.  I moved on this time but next time I'll refer to this for sure.

Nobutaka Kim
Ph: 81-80-7626-1586
Alternate: ***@***.***
Portfolio: https://nyck33.github.io/2021_portfolio/

________________________________
